### PR TITLE
Add useRuntime.ts file at react/components/ folder

### PR DESCRIPTION
**Pull request by estacioneto**
This way, it's types can be generated and shared between VTEX IO apps

### CODE REVIEW

**Comment by lbebber** [comment]
>  it's types can be generated and shared between VTEX IO apps

😮

**Comment by estacioneto** [comment]
Oops... Apparently it didn't work... Moving to WIP

**Comment by lucasecdb** [comment]
@estacioneto can you also do this for `RenderContext`?

**Comment by estacioneto** [comment]
@lucasecdb it's already typed.
```ts
export {default as BuildStatus} from './components/BuildStatus'
export {default as ChildBlock} from './components/ChildBlock'
export {default as ErrorBoundary} from './components/ErrorBoundary'
export {default as LayoutContainer} from './components/LayoutContainer'
export {default as LazyImages} from './components/LazyImages'
export {default as Link} from './components/Link'
export {default as Loading} from './components/Loading'
export {default as LoadingBar} from './components/LoadingBar'
export {default as LoadingContext} from './components/LoadingContext'
export {default as MaybeContext} from './components/MaybeContext'
export {default as NoSSR} from './components/NoSSR'
export {default as RenderContext} from './components/RenderContext'
export {default as RenderPage} from './components/RenderPage'
export {default as RenderProvider} from './components/RenderProvider'
export {default as Session} from './components/Session'
export {default as useRuntime} from './components/useRuntime'
export {}

```

**Pull request merged**
